title: Shinhyeok Oh
url: "https://shinhyeokoh.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: "https://shinhyeokoh.github.io/cv.pdf"

remote_theme: ankitsultana/researcher@gem
google_analytics: 'UA-205864649-1'
